//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dt_Defect> dt_Defect { get; set; }
        public DbSet<dt_Part> dt_Part { get; set; }
        public DbSet<dt_Project> dt_Project { get; set; }
        public DbSet<dt_Service> dt_Service { get; set; }
        public DbSet<dt_User> dt_User { get; set; }
        public DbSet<lu_PartName> lu_PartName { get; set; }
        public DbSet<lu_Region> lu_Region { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tx_DefectService> tx_DefectService { get; set; }
        public DbSet<tx_ServiceParts> tx_ServiceParts { get; set; }
        public DbSet<vW_Arızalar> vW_Arızalar { get; set; }
    }
}
