//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Part
    {
        public dt_Part()
        {
            this.tx_ServiceParts = new HashSet<tx_ServiceParts>();
            this.dt_Project = new HashSet<dt_Project>();
        }
    
        public int PartId { get; set; }
        public Nullable<int> PartTypeId { get; set; }
        public string PartName { get; set; }
        public Nullable<double> PartPrice { get; set; }
        public Nullable<int> PartCount { get; set; }
        public string PriceType { get; set; }
    
        public virtual lu_PartName lu_PartName { get; set; }
        public virtual ICollection<tx_ServiceParts> tx_ServiceParts { get; set; }
        public virtual ICollection<dt_Project> dt_Project { get; set; }
    }
}
