//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Service
    {
        public int ServiceId { get; set; }
        public int ProjectId { get; set; }
        public int ServiceRegionId { get; set; }
        public int ServiceEnteringPersonId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string ServiceNote { get; set; }
    
        public virtual lu_Region lu_Region { get; set; }
    }
}
