//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class lu_PartName
    {
        public lu_PartName()
        {
            this.dt_Part = new HashSet<dt_Part>();
        }
    
        public int PartTypeId { get; set; }
        public string PartTypeName { get; set; }
    
        public virtual ICollection<dt_Part> dt_Part { get; set; }
    }
}
