//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class vW_Arızalar
    {
        public int DefectId { get; set; }
        public int ProjectId { get; set; }
        public string ComplaintDetail { get; set; }
        public string ComplaintName { get; set; }
        public string DefectStatus { get; set; }
        public string DefectNote { get; set; }
        public System.DateTime DefectRecordDate { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> LastModificatorId { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string LastModificationNote { get; set; }
        public string UserName { get; set; }
    }
}
